# Generated by Django 4.1.6 on 2023-07-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(upload_to='upload/customers'),
        ),
    ]
