# Generated by Django 4.1.6 on 2023-07-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
